services:
    db:
        image: mongo:5
        restart: always
        ports:
            - 27017:27017
        environment:
            - MONGODB_DATABASE=nest-dealership
        volumes:
            - ./mongo/data:/dealership-db